### ISSUE TITLE
Hide iframe links on Firefox

### ISSUE THREAD

**Issue by paked** [hackclub/monolith#108]
_From @Bush1do on August 14, 2017 22:35_

Not sure it's just an issue on my browser but these buttons the Hack Club front page aren't functional on Firefox.

![capture](https://user-images.githubusercontent.com/12645067/29294818-45fe73be-811f-11e7-8551-e8ecdc6aa686.PNG)

_Copied from original issue: hackclub/hackclub#1036_

**Comment by paked** [comment]
Thanks for pointing this out @Bush1do!

I'm going to move this issue over to it's relevant repository, namely [monolith](https://github.com/hackclub/monolith).

**Comment by paked** [comment]
@MaxWofford: assigning to you as this is your domain.

**Comment by MaxWofford** [comment]
@paked: Thanks!

@Bush1do: Just tested it in Firefox and also had trouble with the "How It Works" and "See The Clubs" buttons. Was that it, or did you run into issues with the "Our Team" and "Donate" buttons as well?

**Comment by Bush1do** [comment]
@MaxWofford It was all of those buttons

**Comment by MaxWofford** [comment]
@Bush1do: Huh, could you send me the version of Firefox you're using?

**Comment by MaxWofford** [comment]
@Bush1do: ping

**Comment by MaxWofford** [comment]
I'm going to go ahead and change this issue to hiding the broken links on Firefox. Real solution here is just to redo the home page in React without the iframes, but until I have the time to get that done I think hiding these links on Firefox is a good enough stopgap for now.

**Comment by zachlatta** [comment]
![](https://i.giphy.com/media/p0q8UduXdwE80/200.gif)

---

shippin' by day, shippin' by night.
