### ISSUE TITLE
Application year is set to the streak dropdown key in confirmation emails

### ISSUE THREAD

**Issue by MaxWofford** [hackclub/monolith#115]
![screenshot_2017-08-16_08 47 11](https://user-images.githubusercontent.com/5891442/29372380-ca7e9074-825f-11e7-8b32-1a4aeb4f3614.png)

Check out the application confirmation emails to see an example of this ^

**Comment by paked** [comment]
Geh. I thought I fixe thi.

**Comment by paked** [comment]
Can you link an example of this?

Looking through the most recent application we got I cannot see it.

**Comment by paked** [comment]
Closing because this is not an issue.
