### ISSUE TITLE
Authentication not required when accessing some major API endpoints

### ISSUE THREAD

**Issue by ItsDaGeek** [hackclub/monolith#127]
# v1/clubs
### Summary
This endpoint shows sensitive, internal information about *all* clubs

### Reproduce
`curl -X GET https://hackclub.com/v1/clubs`

# v1/clubs
### Summary
Submitting a POST request can alter entries and create entries
### Examples
Look at club.id `114`,`1063`,`1064`

I'll be looking at a bit more later, but these are the most fearing from the bunch.

Credits:
@MaxWofford For confirming results
@paked For egging me on (and backing up the db)

**Comment by paked** [comment]
Fixed with #411e8bd90a74bb75ccd9cd286ba03b18d64ff58d

**Comment by paked** [comment]
Fixed 411e8bd90a74bb75ccd9cd286ba03b18d64ff58d
