### ISSUE TITLE
Emoji do not properly render on workshops pages

### ISSUE THREAD

**Issue by zachlatta** [hackclub/monolith#150]
When I go to https://hackclub.com/workshops, I see `:smile:` instead of the 😊 emoji rendered.

<img width="1552" alt="screen shot 2017-09-04 at 18 33 23" src="https://user-images.githubusercontent.com/992248/30044611-fda1b4ec-91b2-11e7-927d-8da8de7f2779.png">

This can be fixed by properly rendering emoji tags on all workshop pages.

**Comment by magikid** [comment]
This seems to be moot.  I couldn't find any emoji on the pages.  Does it still need to be fixed?

**Comment by MaxWofford** [comment]
@magikid: There's an example at https://hackclub.com/workshops. Search for the text `:warning:` on the page.

**Comment by magikid** [comment]
Yup, I see it now. I'll take a stab at a PR for this.

**Comment by MaxWofford** [comment]
@magikid: Any updates?

**Comment by magikid** [comment]
I wish I had better news but no, no updates.  I thought I would be able to knock this out last weekend but I wasn't able to.  If anyone else wants to take a stab at it, have at it.

**Comment by lachlanjc** [comment]
This is finished! 😃
