### ISSUE TITLE
As CircleCI, I want to cache `bundle install`

### ISSUE THREAD

**Issue by zachlatta** [hackclub/monolith#151]
Currently, CircleCI runs `bundle install` on every build without any caching, which takes ~2 minutes and slows down the overall build.

You can see https://circleci.com/gh/hackclub/monolith/382 for an example of what this looks like:

<img width="1552" alt="screen shot 2017-09-04 at 18 40 48" src="https://user-images.githubusercontent.com/992248/30044643-41b7abaa-91b3-11e7-81f2-d02431d05bd4.png">

This issue can be resolved by having CircleCI cache the installed gems so we don't have to start from scratch on every build.

**Comment by yamilurbina** [comment]
@zachlatta Hi! I've opened a PR that adds the caching on CircleCI for gems. Please check it out.

**Comment by zachlatta** [comment]
Wonderful, thank you so much. Waiting on @paked to check it out, he's the one in charge of the backend.

**Comment by MaxWofford** [comment]
Looks like this was closed by https://github.com/hackclub/monolith/pull/220
