### ISSUE TITLE
As a user on our website, I want to see download as PDF and print buttons on every workshop page

### ISSUE THREAD

**Issue by zachlatta** [hackclub/monolith#154]
As part of our trademark application, we need to add a "Download as PDF" and a "Print" button to our workshop pages to show that our workshops fall within three trademark categories: (1) online curriculum materials, (2) downloadable curriculum materials, and (3) printable physical curriculum materials.

---

As a user, when I go to https://hackclub.com/workshops/personal_website/ or any other workshop on our website, I want to see a "Download as PDF" and a "Print" button somewhere on the page.

Both buttons should be functional and work on all modern browsers. We don't know what browser the person at the trademark office will be using, so we should make sure that it'll definitely work. I have a Browserstack account I can give you access to for testing on different browsers.

Rough mockup of what this could potentially look like:

![mockup](https://user-images.githubusercontent.com/992248/30044697-bade1a1e-91b3-11e7-88db-44a9faa4dc16.png)

This can be resolved once both buttons are live and functional on https://hackclub.com.

**Comment by MaxWofford** [comment]
The print button is in #181
