### ISSUE TITLE
As a teacher, I want to have an explanation for why I can't start a club myself

### ISSUE THREAD

**Issue by zachlatta** [hackclub/monolith#156]
Consider the following:

1. I'm a teacher and hear about starting a Hack Club and am interested
2. I go to https://hackclub.com, click "Start a Hack Club", and am brought to https://hackclub.com/start
3. I read through the page, decide I want to start my application, and say I'm a teacher.
4. When I click through, I'm told that Hack Club only accepts applications from students, but not why that's the case or what I can do to get one started at my high school as a teacher. See screenshots below.

<img width="1552" alt="screen shot 2017-09-04 at 19 01 39" src="https://user-images.githubusercontent.com/992248/30044719-ff5e9d12-91b3-11e7-981c-7803f3f11b8a.png">

<img width="1552" alt="screen shot 2017-09-04 at 19 01 42" src="https://user-images.githubusercontent.com/992248/30044721-01f09652-91b4-11e7-9028-98fbfab6a914.png">

When we reject teachers without a proper explanation, we make it harder for people to start Hack Clubs and establish ourselves as an organization that doesn't care about explaining itself.

To resolve this, we should replace the current text displayed to teachers with a proper explanation for why we believe all Hack Clubs need to be led by students, for students and what they can do as a teacher.

This story can be resolved once new copy has been approved by me and deployed to https://hackclub.com. Ping me on Slack if I can be helpful figuring out what to write here.

**Comment by lachlanjc** [comment]
I think we can close this :+1:

**Comment by MaxWofford** [comment]
Yep! I'd call this finished

<img width="1076" alt="screenshot 2018-03-08 16 36 04" src="https://user-images.githubusercontent.com/5891442/37184178-d091e30a-22ee-11e8-841f-b0ae3473009f.png">
