### ISSUE TITLE
Store information of address in separate DB collumns

### ISSUE THREAD

**Issue by paked** [hackclub/monolith#160]
At the moment we store the addresses of our leaders, clubs and letters as strings and (sometimes) lat/long pairings.

In order for @zachlatta to get proper demographic data about our leaders, we need to have a broken down set of columns containing segments of the addresses which he can query.

The important fields are:

1. Zip/postal code
2. Country
3. State

But getting as many of the other fields as possible is also helpful.

**Comment by MaxWofford** [comment]
Going ahead and adding this to https://github.com/orgs/hackclub/projects/6

**Comment by lachlanjc** [comment]
Is this still to-do?

**Comment by zachlatta** [comment]
Thanks for going through and catching this. Completed now with fields like https://github.com/hackclub/monolith/blob/da6b7b6ba76813e248ab5173780196b189c77775/api/db/schema.rb#L168-L174.
