### ISSUE TITLE
Rewrite home page in React

### ISSUE THREAD

**Issue by MaxWofford** [hackclub/monolith#164]
Right now our home page is sitting in an iframe. This sucks [for](https://github.com/hackclub/monolith/issues/109) [numerous](https://github.com/hackclub/monolith/issues/108) [reasons](https://imgur.com/a/tdTK1) (that I won't get into too much detail on here). I'm making this issue to track a new home page I'm making with React components. Still figuring out all the details to this, so I'll edit the description when I know more.

**Comment by zachlatta** [comment]
Can we close this issue? I don't think it's INVESTable because it's not small.
