### ISSUE TITLE
Automatically schedule the closing and opening of Hackbot check-ins

### ISSUE THREAD

**Issue by paked** [hackclub/monolith#172]
I've been pretty bad at closing and opening check-ins on time for the past couple of weeks.

To solve this, I think we should just automate the entire starting/stopping process: which makes sense, because, well, it's only two jobs that get ran once per week.

So. On Monday 9am PT: `CloseLeaderCheckInsJob` needs to be ran.

And on Thursday at 12pm: `ScheduleLeaderCheckInsJob` needs to be ran.

**Comment by MaxWofford** [comment]
![5220d0a4-d96f-4873-b39d-863bb98e4c82-2113-0000043d1d34bf13](https://user-images.githubusercontent.com/5891442/30279264-9ba55cee-96c1-11e7-989a-3283fe6d0f48.gif)
