### ISSUE TITLE
Send Slack invites from Hackbot

### ISSUE THREAD

**Issue by zachlatta** [hackclub/monolith#178]
Right now, if you fill out https://hackclub.com/slack_invite to get an invite, you get this email:

<img width="992" alt="screen shot 2017-09-12 at 12 57 28" src="https://user-images.githubusercontent.com/992248/30345483-0f25368c-97ba-11e7-825d-6f71264d8896.png">

This sucks and we can make it much nicer by changing the inviter to "Hackbot" and the email to "hackbot@hackclub.com" instead of "Hack Club Admin" and "harrison+hackbot-admin@hackclub.com", respectively.

I've created a Google Group that forwards emails to hackbot@hackclub.com to team@hackclub.com, so everyone on the team has access.

**Comment by MaxWofford** [comment]
Sorry for the label -- that was a misclick.

**Comment by MaxWofford** [comment]
In our new Slack sign up flow the user doesn't see the inviter's name:

![screenshot from 2017-09-27 16-31-25](https://user-images.githubusercontent.com/5891442/30942735-7d9182ae-a3a1-11e7-9846-3dcb62a6ae3f.png)
