### ISSUE TITLE
Refactor web to use only 1 request library

### ISSUE THREAD

**Issue by MaxWofford** [hackclub/monolith#187]
Right now web uses `fetch` `axios` and `superagent` to make requests. This is bad because it over complicates the codebase having to remember the differences between them and choose arbitrarily between which one to use when making a request.

This can be closed once web uses only 1 request library.

**Comment by paked** [comment]
dun dun dun another one bites the dust!

**Comment by lachlanjc** [comment]
This can be closed

**Comment by lachlanjc** [comment]
This can be closed @MaxWofford
