### ISSUE TITLE
Slack is deprecating usernames

### ISSUE THREAD

**Issue by MaxWofford** [hackclub/monolith#189]
Slack usernames are being fazed out in favor of 'display names'. Right now new leaders are being created without usernames and we need to make sure all of api and web are updated to handle the changes.

Here are the notes @paked and I wrote for what needs to be fixed:

[2017-09-13 17.58.39.pdf](https://github.com/hackclub/monolith/files/1305074/2017-09-13.17.58.39.pdf)

**Comment by MaxWofford** [comment]
Fixed by https://github.com/hackclub/monolith/pull/182

**Comment by paked** [comment]
![https://media.giphy.com/media/qOe3IdJvF94fC/giphy.gif](https://media.giphy.com/media/qOe3IdJvF94fC/giphy.gif)

**Comment by paked** [comment]
![https://i.giphy.com/media/qOe3IdJvF94fC/giphy.webp](https://i.giphy.com/media/qOe3IdJvF94fC/giphy.webp)
