### ISSUE TITLE
Workshop headers should be linkable

### ISSUE THREAD

**Issue by MaxWofford** [hackclub/monolith#230]
GitHub has a nifty little link next to all their headers in Markdown so people can copy links directly to them:
![screenshot from 2017-10-03 10-30-57](https://user-images.githubusercontent.com/5891442/31139299-f646f1ec-a825-11e7-9330-fc951ff44269.png)

It'd be awesome if https://hackclub.com/workshops also had a way for getting links to headers.

**Comment by makketagg** [comment]
Hey @MaxWofford. Do you want to use [.octicon-link](https://octicons.github.com/icon/link/)? Or just clickable links?

**Comment by MaxWofford** [comment]
@makketagg it'd be great to have octicon-link icons.

**Comment by makketagg** [comment]
@MaxWofford i will take this task 👌

**Comment by lachlanjc** [comment]
This is finished!
