### ISSUE TITLE
Orpheus should interpret messages as "yes" if their first word is yes

### ISSUE THREAD

**Issue by zachlatta** [hackclub/monolith#238]
Example from Lachlan's check-ins this week:

<img width="834" alt="lachlan" src="https://user-images.githubusercontent.com/992248/31309915-250af1d4-ab43-11e7-886b-28cf2be70986.png">

**Comment by zachlatta** [comment]
Think this should be pretty easy, just modifying the regex here: https://github.com/hackclub/monolith/blob/e046b3ed3277e57dd99b53ee89a46235e786c0f6/api/app/models/hackbot/utterances.rb#L10

**Comment by zachlatta** [comment]
@MaxWofford: have you tested this / can we close this issue?

**Comment by MaxWofford** [comment]
Waiting on @paked to review and merge
