### ISSUE TITLE
Snyk does not appear to work in docker

### ISSUE THREAD

**Issue by caseyprovost** [hackclub/monolith#251]
### Overview
I followed the provided setup instructions for the web component, and upon trying to run the docker-compose build web command I got the following output:
(I am on a mac from Jan 2017)

![screen shot 2017-10-12 at 3 37 59 pm](https://user-images.githubusercontent.com/210048/31515501-5a6aa18e-af63-11e7-96bd-8287b1842ae9.png)

**Comment by MaxWofford** [comment]
@caseyprovost Thanks for catching this! Will check this out when I can. For the time being you can delete this line while developing https://github.com/hackclub/monolith/blob/master/web/package.json#L41. It's a hack but it'll let you get up and running for the time being.
