### ISSUE TITLE
Setup instructions in README fail on a new clone

### ISSUE THREAD

**Issue by zachlatta** [hackclub/monolith#32]
The setup instructions in `README.md` fail when you create a clean clone. `frontend` fails to launch because `react-scripts` is missing.

Steps to reproduce:

1. Clone `monolith`
2. Add `.env` files to `frontend/` and `api/` with appropriate contents
3. Run the following commands:

   1. `docker-compose build`
   2. `docker-compose run api bundle`
   3. `docker-compose run api rails db:create db:migrate`
   4. `docker-compose up`

4. Notice that the `frontend` service fails to launch.

**Comment by paked** [comment]
I thought this was intended behaviour?

**Comment by zachlatta** [comment]
How is this intended behavior? When following the setup guide, I expect it to setup my application. Not continue to fail to launch.
