### ISSUE TITLE
Fix read only Streak values being evaluated at the wrong time

### ISSUE THREAD

**Issue by paked** [hackclub/monolith#62]
There is currently a bug with our Streak syncing code that will evaluate read-only values before everything else.

This is a problem because often these read-only values require the latest information in order to parse their results, and in an environment where this information is often assumed to not be nil this can be very bad.

 Example: We're loading a bunch of new data into the database, but Streak because read only field `X` relies on `Z`, and `Z` has not been set from in the DB yet `X` will throw a `nil value` error.

**Comment by MaxWofford** [comment]
What specific fields are affected?

**Comment by paked** [comment]
Closing because this isn't _actually_ a problem
