### ISSUE TITLE
Submit buttons on the frontend shouldn't submit when loading

### ISSUE THREAD

**Issue by MaxWofford** [hackclub/monolith#95]
Right now clicking on the submit button on https://hackclub.com/apply while it's loading submits multiple applications.

**Comment by paked** [comment]
@MaxWofford: Wasn't this fixed?

**Comment by MaxWofford** [comment]
https://github.com/hackclub/monolith/commit/5adeb455ef3a23b380c96a9159bdfec7dace1a6c
